dependencies:
  - name: elasticsearch
    repository: https://helm.elastic.co
    version: 7.6.0
    condition: elasticsearch.enabled
    import-values:
      - child: volumeClaimTemplate
        parent: elasticVolumeClaimTemplate
  - name: memcached
    version: 4.2.6
    repository: https://charts.bitnami.com
    condition: memcached.enabled
  - name: postgresql
    version: 8.3.4
    repository: https://charts.bitnami.com
    condition: postgresql.enabled
    import-values:
      - child: persistence.storageClass
        parent: defaultStorageClass
      - child: persistence.size
        parent: defaultStorageSize
